// packages/grid-wc/examples/react/pagination/App.tsx
import { SvGrid } from '@svgrid/grid-wc/react'
import { people, columns } from '../data'

/**
 * Client-side paging. `pageSize` is read once at mount - it is the INITIAL
 * page size - so change pages through the footer or the grid api rather than
 * by reassigning the prop.
 */
export default function App() {
  return (
    <div style={{ height: '100%', padding: 16 }}>
      <SvGrid
        data={people}
        columns={columns}
        sortable
        filterable
        pageable
        pageSize={25}
        pageSizeOptions={[10, 25, 50, 100]}
        paginationPosition="bottom"
      />
    </div>
  )
}

// packages/grid-wc/examples/svelte/pagination/App.svelte
<script lang="ts">
  /**
   * Mirrors examples/react/pagination/App.tsx.
   *
   * `pageSize` is the INITIAL page size, read once at mount, so paging happens
   * through the footer rather than by reassigning the prop.
   */
  import GridBody from '../../../src/GridBody.svelte'
  import { people, columns } from '../data'
</script>

<div class="mirror">
  <div class="mirror-grid">
    <GridBody
      emit={() => {}}
      data={people}
      {columns}
      sortable
      filterable
      pageable
      pageSize={25}
      pageSizeOptions={[10, 25, 50, 100]}
      paginationPosition="bottom"
    />
  </div>
</div>

<style>
  .mirror {
    display: flex;
    flex-direction: column;
    gap: 12px;
    height: 100%;
    /* min-width, not just min-height: this is a flex item, and a flex item's
       automatic minimum size is its MIN-CONTENT width, which for a grid is the
       sum of its column widths. Without this it can never be laid out narrower
       than its widest possible self. */
    min-width: 0;
  }
  .mirror-grid {
    flex: 1;
    min-width: 0;
    min-height: 0;
  }
</style>
