// packages/grid-wc/examples/vue/basic/App.vue
<script setup lang="ts">
// The smallest useful grid: rows, columns, and the two features almost every
// table wants. The wrapper forwards arrays as DOM properties, so no `.prop`
// modifier and no `isCustomElement` build config.
import { SvGrid } from '@svgrid/grid-wc/vue'
import { people, columns } from '../data'
</script>

<template>
  <div style="height: 100%; padding: 16px">
    <SvGrid :data="people" :columns="columns" sortable filterable />
  </div>
</template>

// packages/grid-wc/examples/react/basic/App.tsx
import { SvGrid } from '@svgrid/grid-wc/react'
import { people, columns } from '../data'

/**
 * The smallest useful grid: rows, columns, and the two features almost every
 * table wants. `data` and `columns` are arrays, so they cross as properties -
 * the wrapper handles that on every React version.
 */
export default function App() {
  return (
    <div style={{ height: '100%', padding: 16 }}>
      <SvGrid data={people} columns={columns} sortable filterable />
    </div>
  )
}
